<a href="https://colab.research.google.com/github/iakshaykr/AI_ML/blob/main/TF2_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To Install TF 2 in your local machine : https://www.tensorflow.org/install

In [3]:
!pip show pip

Name: pip
Version: 23.1.2
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: distutils-sig@python.org
License: MIT
Location: /usr/local/lib/python3.10/dist-packages
Requires: 
Required-by: fastai, pip-tools


In [4]:
!pip show tensorflow

Name: tensorflow
Version: 2.15.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/lib/python3.10/dist-packages
Requires: absl-py, astunparse, flatbuffers, gast, google-pasta, grpcio, h5py, keras, libclang, ml-dtypes, numpy, opt-einsum, packaging, protobuf, setuptools, six, tensorboard, tensorflow-estimator, tensorflow-io-gcs-filesystem, termcolor, typing-extensions, wrapt
Required-by: dopamine_rl, tf_keras


In [5]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [6]:
import tensorflow as tf
import numpy as np
tf.debugging.set_log_device_placement(True)

In [16]:
tf.executing_eagerly()

True

Single Dimensional Array : Rank 0 - scalar   x=tf.constant(3)shape = ()

In [34]:
x0=tf.constant(3)
print(x0)

tf.Tensor(3, shape=(), dtype=int32)


In [35]:
x0.shape

TensorShape([])

In [10]:
x0.dtype

tf.int32

In [11]:
x0.numpy()

3

In [12]:
res=x0+10
res

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(), dtype=int32, numpy=13>

Rank 1 - vector  

  x=tf.constant([3,5,7])  shape = (3,)

In [13]:
x1=tf.constant([1.1,2.2,3.3,4.4])
x1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 2.2, 3.3, 4.4], dtype=float32)>

In [14]:
res0=x1+5
res0

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [15]:
res0=tf.add(x1 , tf.constant(5.0))
res0

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

Rank 2 - matrix    x=tf.constant([3,5,7],[4,6,8]) shape = (2,3)

In [16]:
res1=tf.constant([[2,2,4,5],[5,5,7,9]])
res1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[2, 2, 4, 5],
       [5, 5, 7, 9]], dtype=int32)>

In [17]:
tf.is_tensor(res1)

True

In [18]:
res1.shape

TensorShape([2, 4])

In [19]:
tf.convert_to_tensor(res1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[2, 2, 4, 5],
       [5, 5, 7, 9]], dtype=int32)>

In [20]:
res1

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[2, 2, 4, 5],
       [5, 5, 7, 9]], dtype=int32)>

In [21]:
res1.numpy()

array([[2, 2, 4, 5],
       [5, 5, 7, 9]], dtype=int32)

In [22]:
t0 = tf.zeros([3, 5], tf.int32)

t0

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

In [23]:
t1 = tf.ones([3, 5], tf.int32)

t1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)>

In [3]:
import tensorflow as tf
import numpy as np

In [4]:
v1 = tf.Variable([[1.5, 2, 5], [2, 6, 8]])

v1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 8. ]], dtype=float32)>

In [5]:
v2 = tf.Variable([[1, 2, 3], [4, 5, 6]])

v2

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [8]:
v2 = tf.Variable([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)

v2

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [9]:
tf.add(v1, v2)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.5,  4. ,  8. ],
       [ 6. , 11. , 14. ]], dtype=float32)>

In [10]:
tf.convert_to_tensor(v1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 8. ]], dtype=float32)>

In [11]:
v1.numpy()

array([[1.5, 2. , 5. ],
       [2. , 6. , 8. ]], dtype=float32)

In [12]:
v1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 8. ]], dtype=float32)>

In [13]:
v1.assign([[10, 20, 30], [40, 50, 60]])

v1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[10., 20., 30.],
       [40., 50., 60.]], dtype=float32)>

In [14]:
v1[0, 0].assign(100)

v1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[100.,  20.,  30.],
       [ 40.,  50.,  60.]], dtype=float32)>

In [15]:
v1.assign_add([[1, 1, 1], [1, 1, 1]])

v1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[101.,  21.,  31.],
       [ 41.,  51.,  61.]], dtype=float32)>

In [18]:
%load_ext tensorboard

In [27]:
%tensorboard --logdir="./logs" dev 6060

ERROR: Failed to launch TensorBoard (exited with 2).
Contents of stderr:
2024-07-13 16:14:17.135261: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-13 16:14:17.135342: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-13 16:14:17.136684: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-13 16:14:18.498244: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
usage: tensorboard dev [-h] [--helpfull] [--origin ORIGIN] [--api_endpoint API_ENDPOINT]
                       [--grpc_creds_type {local,ssl,ssl_dev}] [--auth_force_co

In [23]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  0


In [25]:
import tensorflow as tf
print("Num CPUs Available: ", len(tf.config.list_physical_devices('CPU')))

Num CPUs Available:  1


In [29]:
y=tf.constant([[4,5,6],[4,5,6]])
y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [4, 5, 6]], dtype=int32)>

In [30]:
y.shape

TensorShape([2, 3])

In [33]:
x=tf.add(y,10)
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[14, 15, 16],
       [14, 15, 16]], dtype=int32)>